require './db/seeds/production/location_types'
require './db/seeds/production/activities/anywhere'
require './db/seeds/production/activities/bakery'
require './db/seeds/production/activities/book_store'
require './db/seeds/production/activities/cafe'
require './db/seeds/production/activities/park'
require './db/seeds/production/activities/spa'
require './db/seeds/production/activities/tourist_attraction'