// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SetStartPointController from "./set_start_point_controller"
application.register("set-start-point", SetStartPointController)

import ShowMapController from "./show_map_controller"
application.register("show-map", ShowMapController)
