version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/walking_lot:cached
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
      - chrome
      - redis
      - sidekiq
    stdin_open: true
    tty: true
    environment:
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
      REDIS_URL: redis://redis:6379
      SIDEKIQ_ADMIN_BASIC_AUTH_USER: sidekiq
      SIDEKIQ_ADMIN_BASIC_AUTH_PASSWORD: password
  db:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    # command: mysqld --default-time-zone=Asia/Tokyo
  chrome:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - 4444:4444
  sidekiq:
    build: .
    environment:
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/walking_lot:cached
      - bundle:/usr/local/bundle
    depends_on:
      - db
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  bundle:
  mysql_data:
  redis: