version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/walking_lot:cached
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
      - chrome
    stdin_open: true
    tty: true
    environment:
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
  db:
    image: mysql:5.7.33
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  chrome:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - 4444:4444
volumes:
  bundle:
  mysql_data: